steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/deepvision-deploy/github.com/satyak2003/deepvision-detectionofdeepfakes', 'gcr.io/deepvision-deploy/github.com/satyak2003/deepvision-detectionofdeepfakes/backend']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/deepvision-deploy/github.com/satyak2003/deepvision-detectionofdeepfakes']
options:
 defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET