FROM python:3.11-slim

WORKDIR /backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install gunicorn

COPY . .

CMD gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 app:app