FROM python:3.11-slim

WORKDIR /backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install gunicorn

COPY . .

EXPOSE 7860

CMD gunicorn --bind 0.0.0.0:7860 --workers 1 --timeout 300 app:app